{% set name = "gspread-pandas" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ad1390124b95b2bb522f1e9ea5f16af88e9c2ef47aa7f10bbfdec4d4b7607717

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - decorator
    - future
    - google-auth
    - google-auth-oauthlib
    - gspread >=3.0.0
    - pandas >=0.20.0
    - pathlib2  # [py27]

test:
  imports:
    - gspread_pandas
  requires:
    - pytest

about:
  home: https://github.com/aiguofer/gspread-pandas
  license: BSD
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package to easily open an instance of a Google spreadsheet and interact with worksheets through Pandas DataFrames.
  doc_url: https://gspread-pandas.readthedocs.io/en/latest
  dev_url: https://github.com/aiguofer/gspread-pandas

extra:
  recipe-maintainers:
    - mariusvniekerk
