travis:
  secure:
    BINSTAR_TOKEN: ZnrnL1gcp1zG5Bt3pJOUWjDTwD/vhJlmePCCH/vqJErNpWODJpfZwVdoxOcq7eyASCx2HTcSDaSqm7NokrBTf40JmpRFCevXpUr8T8DW3STmgcWzxw+n0Reo8QLmYzm3HijKGrT5vCrX6qZnOBR0DJSP7HqIjaKK7b7bYAhLBEI7lVG3Zdg0QRJWJU3bC5hjVlmq3Iusq1OkhY92VZfYJbK8hQn4YAqUsSYhcjnxxFBk/cmhqfyxR+WRjg3D20LQnNHUVT3N826zxp+Qzho9yyd403EKhIY5f+q08RVMzB08WiCQaW0x9KPH9PrwVNzP8QG0YfiGfNkWMf6D0pkrCM+uomNhsFjWqLcESkfkGf9RgM47m857vx1ni633YQl57331okUSZfQHlAnzB+WM2VeYJ/Ee/xh+A4DdsPNfpe/2H4VxNpzczXZndjA/rMeA5jUiYdwGWKZEtd3YPXS0f9h5KLj+fOkVWurGjNsDxPHi4mSySqbjfGTsOoecnoWgSFy0UEoVwGZBF9VwfYGy8ANZd16XauE/MeqGAYXAhLzdSmisQsVVsLLuSiav56QFhu4EI9VJXdkLNTmYYKdpDSGywVLlXgLbW9FMuz/uR63L2gpNf8obPqYa70JDiJ07KYjyKNWv76JSRpGnsU1QQMANVHuOb0xBb1MUQUuKqyo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
