travis:
  secure:
    BINSTAR_TOKEN: rV1LMlgHK4oJXkeYUduoFGNR0CY0m2LHbmPEM9c3YwaCSsvdfxntv69KNVU4sBJhJdw4kzx3y+1VukBr8w0+8t7b6Y5slfkRVnhdisSpm0UQn5irI1PcUjX3twqXq8PN92jFEBXXujiCGec/1qFEnix2xyete1h/boIco8Ls4Vj2nLVtp31LYVaY5wN+FVFZQUKVHwwlYzN83YchDvRgy6SwSB41lpYV2xBQRyH06GD0vOwGBEXREJtrN5WGL3+fGNq9eL9uKxbWIZvdPw+J0QBVuzngomf5rx5wl/ZyMlAbXtz1oblfSW8RTnDh9bithv0BB1o9leXVs0mcx2KiHkrNOV2NKg/n/VVn4WJd/kCXJPwllQzh/vfnICmqpa6e0kDFA3RguKmbHu4n/hZbzJZPcZNYhWu+igv8LxIDJVMb3cpJMzCRJiY2qytYpAeGZtMEbuf74dp9fPHCDf2JzkUXZYhmKOrgCPH0R/WGlp/9QoCOj0gu+Tr63/mfsoJgi0UysKqMDTKmu2nskqkg6DMy1Hkh34u5TFqDZM5mz1H2m2cuN2sAYCetfI/RwnrOzO6inUwr4yGhyGYnAwsZmldoAF68+538oGEPB2ZzDKemNRl3i4pZJr6o4b9YAfNF8iTEJ69oLTKaTCLqYBPEvmAnUCw2jlDYVVVXZlqciIE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
